// Comprehensive Skills Database - All majors and fields worldwide
// Organized by industry/major for easy suggestions

export const skillsDatabase = {
  // Technology & Computer Science
  technology: {
    label: 'Technology & Computer Science',
    skills: [
      // Programming Languages
      'Python',
      'JavaScript',
      'TypeScript',
      'Java',
      'C++',
      'C#',
      'Go',
      'Rust',
      'PHP',
      'Ruby',
      'Swift',
      'Kotlin',
      'R',
      'MATLAB',
      'Scala',
      'Haskell',
      'Perl',
      'Groovy',
      'Dart',
      'Elixir',

      // Frontend
      'React',
      'Vue.js',
      'Angular',
      'Svelte',
      'Next.js',
      'Nuxt.js',
      'HTML',
      'CSS',
      'Tailwind CSS',
      'Bootstrap',
      'Material-UI',
      'SASS',
      'Less',
      'Redux',
      'Vuex',
      'Pinia',
      'Context API',
      'MobX',

      // Backend
      'Node.js',
      'Express',
      'Django',
      'Flask',
      'FastAPI',
      'Spring Boot',
      'Ruby on Rails',
      'ASP.NET',
      'Symfony',
      'Laravel',
      'NestJS',
      'GraphQL',
      'REST APIs',
      'gRPC',
      'SOAP',
      'WebSockets',

      // Databases
      'MongoDB',
      'PostgreSQL',
      'MySQL',
      'SQL Server',
      'Oracle',
      'SQLite',
      'Firebase',
      'DynamoDB',
      'Cassandra',
      'Redis',
      'Elasticsearch',
      'Neo4j',
      'Couchbase',
      'MariaDB',
      'InfluxDB',
      'TimeSeriesDB',

      // Cloud & DevOps
      'AWS',
      'Google Cloud',
      'Azure',
      'Docker',
      'Kubernetes',
      'Jenkins',
      'GitLab CI',
      'GitHub Actions',
      'CircleCI',
      'Travis CI',
      'Terraform',
      'CloudFormation',
      'Ansible',
      'Puppet',
      'Chef',
      'Helm',
      'Prometheus',
      'Grafana',
      'ELK Stack',
      'New Relic',
      'Datadog',

      // Mobile Development
      'React Native',
      'Flutter',
      'Swift',
      'Kotlin',
      'Xamarin',
      'Ionic',
      'Expo',
      'Android Development',
      'iOS Development',
      'Cross-platform',

      // AI/ML
      'Machine Learning',
      'Deep Learning',
      'TensorFlow',
      'PyTorch',
      'Keras',
      'Scikit-learn',
      'XGBoost',
      'Neural Networks',
      'NLP',
      'Computer Vision',
      'OpenCV',
      'Pandas',
      'NumPy',
      'SciPy',
      'Jupyter',
      'Data Science',
      'Statistics',
      'Predictive Analytics',
      'Reinforcement Learning',
      'LLMs',
      'Transformers',
      'BERT',
      'GPT',
      'Hugging Face',

      // Version Control & Tools
      'Git',
      'GitHub',
      'GitLab',
      'Bitbucket',
      'SVN',
      'Mercurial',
      'Jira',
      'Confluence',
      'Slack',
      'Trello',
      'Asana',
      'Monday.com',
      'Linear',

      // Testing
      'Unit Testing',
      'Integration Testing',
      'E2E Testing',
      'Jest',
      'Mocha',
      'Pytest',
      'JUnit',
      'Selenium',
      'Cypress',
      'Playwright',
      'TestNG',
      'RSpec',
      'Jasmine',
      'Vitest',
      'Test Coverage',

      // Architecture
      'Microservices',
      'Monolithic',
      'Serverless',
      'Event-Driven',
      'MVC',
      'MVVM',
      'Clean Architecture',
      'Hexagonal Architecture',
      'SOA',

      // Other Tech
      'Blockchain',
      'Smart Contracts',
      'Solidity',
      'Web3',
      'Cryptocurrency',
      'AR/VR',
      'Game Development',
      'Unity',
      'Unreal Engine',
      'WebGL',
      'Data Visualization',
      'D3.js',
      'Plotly',
      'Tableau',
      'Power BI',
    ],
  },

  // Data Science & Analytics
  datascience: {
    label: 'Data Science & Analytics',
    skills: [
      'Python',
      'R',
      'SQL',
      'Data Analysis',
      'Statistical Analysis',
      'Data Visualization',
      'Pandas',
      'NumPy',
      'Matplotlib',
      'Seaborn',
      'Plotly',
      'Tableau',
      'Power BI',
      'Looker',
      'Apache Spark',
      'Data Mining',
      'ETL',
      'Data Pipeline',
      'Big Data',
      'Hadoop',
      'Machine Learning',
      'Deep Learning',
      'TensorFlow',
      'PyTorch',
      'Scikit-learn',
      'Business Intelligence',
      'Predictive Modeling',
      'Time Series Analysis',
      'Regression',
      'Classification',
      'Clustering',
      'NLP',
      'Computer Vision',
      'A/B Testing',
      'Experimentation',
      'Excel',
      'Google Analytics',
      'Mixpanel',
      'Amplitude',
      'Segment',
    ],
  },

  // Business & Management
  business: {
    label: 'Business & Management',
    skills: [
      'Project Management',
      'Product Management',
      'Business Strategy',
      'Business Analysis',
      'Market Research',
      'Competitive Analysis',
      'Financial Analysis',
      'Budgeting',
      'Forecasting',
      'Excel',
      'Power Point',
      'Presentation Skills',
      'Stakeholder Management',
      'Risk Management',
      'Supply Chain Management',
      'Operations Management',
      'Quality Management',
      'Six Sigma',
      'Lean Management',
      'Agile',
      'Scrum',
      'Kanban',
      'SAP',
      'Oracle NetSuite',
      'Salesforce',
      'HubSpot',
      'Customer Success',
      'Account Management',
      'B2B',
      'B2C',
      'SaaS',
      'Strategic Planning',
      'Change Management',
      'Business Process',
      'Workflow',
      'Optimization',
      'Efficiency',
    ],
  },

  // Design & UX
  design: {
    label: 'Design & UX/UI',
    skills: [
      'UI Design',
      'UX Design',
      'Figma',
      'Adobe XD',
      'Sketch',
      'InVision',
      'Wireframing',
      'Prototyping',
      'User Research',
      'User Testing',
      'Usability Testing',
      'A/B Testing',
      'Accessibility',
      'WCAG',
      'Design Systems',
      'Component Design',
      'Responsive Design',
      'Mobile Design',
      'Web Design',
      'Interaction Design',
      'Animation',
      'Motion Design',
      'Adobe Creative Suite',
      'Photoshop',
      'Illustrator',
      'InDesign',
      'Premiere Pro',
      'After Effects',
      'Visual Design',
      'Color Theory',
      'Typography',
      'Layout',
      'Branding',
      'Design Thinking',
      'Persona Development',
      'Journey Mapping',
      'Information Architecture',
      'Sitemap Design',
      'Mockup',
      'Design Critique',
    ],
  },

  // Marketing & Communications
  marketing: {
    label: 'Marketing & Communications',
    skills: [
      'Digital Marketing',
      'Content Marketing',
      'Social Media Marketing',
      'Email Marketing',
      'SEO',
      'SEM',
      'PPC',
      'Google Ads',
      'Facebook Ads',
      'Instagram Marketing',
      'LinkedIn Marketing',
      'TikTok Marketing',
      'Content Strategy',
      'Content Writing',
      'Copywriting',
      'Brand Strategy',
      'Brand Management',
      'Marketing Analytics',
      'Google Analytics',
      'Marketing Automation',
      'HubSpot',
      'Mailchimp',
      'Customer Relationship',
      'Influencer Marketing',
      'Affiliate Marketing',
      'Growth Hacking',
      'Conversion Rate Optimization',
      'Market Research',
      'Competitive Analysis',
      'Campaign Management',
      'Event Marketing',
      'PR',
      'Public Relations',
      'Communication',
      'Presentation',
      'Negotiation',
      'Sales',
    ],
  },

  // Finance & Accounting
  finance: {
    label: 'Finance & Accounting',
    skills: [
      'Financial Analysis',
      'Financial Modeling',
      'Valuation',
      'DCF',
      'Accounting',
      'Bookkeeping',
      'GAAP',
      'IFRS',
      'Financial Reporting',
      'Auditing',
      'Internal Audit',
      'Risk Assessment',
      'Compliance',
      'Taxation',
      'Tax Planning',
      'Budget Management',
      'Forecasting',
      'Excel',
      'Python',
      'R',
      'SQL',
      'Power BI',
      'Tableau',
      'QuickBooks',
      'SAP',
      'Oracle',
      'Workday',
      'Bloomberg Terminal',
      'Securities Analysis',
      'Portfolio Management',
      'Investment Analysis',
      'Capital Markets',
      'Derivatives',
      'Fixed Income',
      'Equity Research',
      'Credit Analysis',
      'Risk Management',
      'Corporate Finance',
      'M&A',
    ],
  },

  // Engineering & Manufacturing
  engineering: {
    label: 'Engineering & Manufacturing',
    skills: [
      // Mechanical
      'AutoCAD',
      'CAD',
      'SolidWorks',
      'CATIA',
      'NX',
      'Inventor',
      'Mechanical Design',
      'Machine Design',
      'Thermodynamics',
      'Fluid Dynamics',
      'Structural Analysis',
      'FEA',
      'CFD',
      'MATLAB',
      'Simulation',
      'Manufacturing',
      'CNC',
      'Welding',
      'Machining',
      'Quality Control',

      // Civil
      'Civil Engineering',
      'Structural Engineering',
      'Building Design',
      'Infrastructure',
      'Project Management',
      'BIM',
      'Revit',
      'Autocad',
      'SAP2000',
      'ETABS',
      'Staad Pro',
      'Geotechnical',
      'Foundation Design',
      'Surveying',
      'Construction Management',

      // Electrical
      'Electrical Engineering',
      'Circuit Design',
      'Power Systems',
      'Power Electronics',
      'Control Systems',
      'Signal Processing',
      'Embedded Systems',
      'Microcontrollers',
      'Arduino',
      'PLC',
      'SCADA',
      'Industrial Automation',
      'Renewable Energy',
      'Solar Systems',
      'Wind Energy',
      'SPICE',
      'Cadence',

      // Software Engineering
      'Software Development',
      'Software Architecture',
      'Code Review',
      'Technical Documentation',
      'API Design',
      'System Design',
      'Software Testing',
      'Debugging',
      'Performance Optimization',
      'Refactoring',
      'Clean Code',
      'Design Patterns',
      'SOLID Principles',
    ],
  },

  // Healthcare & Life Sciences
  healthcare: {
    label: 'Healthcare & Life Sciences',
    skills: [
      'Clinical Research',
      'Medical Device',
      'Pharmaceutical',
      'Biotech',
      'Biotechnology',
      'Molecular Biology',
      'Genetics',
      'Genomics',
      'Bioinformatics',
      'Protein Engineering',
      'Cell Biology',
      'Microbiology',
      'Immunology',
      'Pharmacology',
      'Clinical Trials',
      'Healthcare IT',
      'EHR',
      'HIPAA',
      'Medical Coding',
      'Healthcare Analytics',
      'Nursing',
      'Patient Care',
      'Diagnostic Imaging',
      'Pathology',
      'Surgery',
      'Anesthesia',
      'Cardiology',
      'Oncology',
      'Pediatrics',
    ],
  },

  // Education & Academia
  education: {
    label: 'Education & Academia',
    skills: [
      'Teaching',
      'Curriculum Design',
      'Instructional Design',
      'E-Learning',
      'Learning Management Systems',
      'Canvas',
      'Blackboard',
      'Moodle',
      'Course Development',
      'Student Assessment',
      'Educational Psychology',
      'Pedagogy',
      'STEM Education',
      'Mentoring',
      'Tutoring',
      'Academic Research',
      'Research Paper Writing',
      'Citation Management',
      'Zotero',
      'Mendeley',
      'Literature Review',
      'Grant Writing',
    ],
  },

  // Sales & Customer Service
  sales: {
    label: 'Sales & Customer Service',
    skills: [
      'Sales',
      'B2B Sales',
      'B2C Sales',
      'Solution Selling',
      'Consultative Selling',
      'Account Management',
      'Customer Success',
      'Client Relationship',
      'CRM',
      'Salesforce',
      'HubSpot',
      'Pipedrive',
      'Zoho CRM',
      'Negotiation',
      'Closing Techniques',
      'Objection Handling',
      'Sales Pipeline',
      'Lead Generation',
      'Cold Calling',
      'Email Outreach',
      'Customer Service',
      'Support Ticket',
      'Ticketing System',
      'Chat Support',
      'Knowledge Management',
      'Empathy',
      'Problem Solving',
      'Patience',
    ],
  },

  // Human Resources
  humanresources: {
    label: 'Human Resources',
    skills: [
      'Recruitment',
      'Talent Acquisition',
      'Sourcing',
      'Job Description',
      'Interviewing',
      'Candidate Assessment',
      'Employer Branding',
      'Employee Relations',
      'Performance Management',
      'Training & Development',
      'Learning & Development',
      'Onboarding',
      'Offboarding',
      'Compensation & Benefits',
      'Payroll',
      'HR Analytics',
      'Metrics',
      'HRIS',
      'Workday',
      'SAP SuccessFactors',
      'BambooHR',
      'Employee Engagement',
      'Retention',
      'Compliance',
      'Labor Law',
      'Conflict Resolution',
      'Mediation',
      'Organizational Development',
    ],
  },

  // Legal
  legal: {
    label: 'Legal',
    skills: [
      'Contract Law',
      'Corporate Law',
      'Intellectual Property',
      'Patent Law',
      'Trademark Law',
      'Copyright',
      'Litigation',
      'Dispute Resolution',
      'Arbitration',
      'Mediation',
      'Employment Law',
      'Labor Law',
      'Tax Law',
      'Real Estate Law',
      'International Law',
      'Compliance',
      'Regulatory',
      'Document Review',
      'Legal Writing',
      'Research',
      'Legal Research',
      'Case Law',
      'Legislation',
      'E-Discovery',
      'Legal Tech',
      'Contract Management',
      'Risk Management',
    ],
  },

  // Supply Chain & Logistics
  supplychain: {
    label: 'Supply Chain & Logistics',
    skills: [
      'Supply Chain Management',
      'Logistics',
      'Inventory Management',
      'Procurement',
      'Vendor Management',
      'Purchasing',
      'Sourcing',
      'Demand Planning',
      'Forecasting',
      'Production Planning',
      'Warehouse',
      'Distribution',
      'Transportation',
      'Shipping',
      'Customs',
      'International Trade',
      'SAP',
      'Oracle',
      'JDA',
      'Blue Yonder',
      'ERP',
      'Supply Chain Analytics',
      'Business Intelligence',
      'Process Optimization',
      'Six Sigma',
      'Lean Management',
      'Quality Management',
      'Sustainability',
      'Risk Management',
    ],
  },

  // Environmental & Sustainability
  sustainability: {
    label: 'Environmental & Sustainability',
    skills: [
      'Environmental Science',
      'Climate Change',
      'Sustainability',
      'Carbon Footprint',
      'ESG',
      'Renewable Energy',
      'Solar',
      'Wind',
      'Energy Efficiency',
      'Waste Management',
      'Recycling',
      'Circular Economy',
      'Environmental Compliance',
      'EIA',
      'GIS',
      'Data Analysis',
      'Environmental Policy',
      'Advocacy',
      'Community Engagement',
      'Green Building',
      'LEED',
      'Ecology',
      'Conservation',
    ],
  },

  // Media & Entertainment
  media: {
    label: 'Media & Entertainment',
    skills: [
      'Video Production',
      'Photography',
      'Editing',
      'Adobe Premiere',
      'Final Cut Pro',
      'DaVinci Resolve',
      'Motion Graphics',
      'Animation',
      'After Effects',
      '3D Animation',
      'Blender',
      'Cinema 4D',
      'Maya',
      'Sound Design',
      'Audio Editing',
      'Podcasting',
      'Broadcasting',
      'Content Creation',
      'Social Media Content',
      'Streaming',
      'Game Development',
      'Unity',
      'Unreal Engine',
      'Storytelling',
      'Screenwriting',
      'Storyboarding',
      'Photography',
      'Cinematography',
    ],
  },

  // Writing & Journalism
  writing: {
    label: 'Writing & Journalism',
    skills: [
      'Writing',
      'Technical Writing',
      'Content Writing',
      'Copywriting',
      'Journalism',
      'Reporting',
      'Investigative Journalism',
      'Editorial Skills',
      'Fact-checking',
      'Research',
      'Interview',
      'Publishing',
      'Editing',
      'Proofreading',
      'Grammar',
      'AP Style',
      'Chicago Manual of Style',
      'MLA',
      'APA',
      'Blogging',
      'Ghostwriting',
      'Screenwriting',
      'Playwriting',
      'Poetry',
      'Fiction Writing',
      'Non-fiction',
      'Memoir',
    ],
  },

  // Hospitality & Tourism
  hospitality: {
    label: 'Hospitality & Tourism',
    skills: [
      'Hotel Management',
      'Restaurant Management',
      'Chef',
      'Cooking',
      'Culinary Arts',
      'Food Service',
      'Bartending',
      'Event Planning',
      'Customer Service',
      'Hospitality',
      'Tourism Management',
      'Travel Planning',
      'Booking Systems',
      'Guest Relations',
      'Property Management',
      'Housekeeping',
      'Maintenance',
      'Inventory Management',
      'POS Systems',
      'Revenue Management',
      'Marketing',
      'Social Media',
    ],
  },

  // Architecture
  architecture: {
    label: 'Architecture',
    skills: [
      'Architectural Design',
      'Building Design',
      'Urban Planning',
      'Landscape Architecture',
      'CAD',
      'AutoCAD',
      'Revit',
      'BIM',
      'SketchUp',
      'Rendering',
      'Visualization',
      'Sketching',
      'Building Codes',
      'Zoning',
      'Structural Knowledge',
      'Material Knowledge',
      'Project Management',
      'Construction Administration',
      'Client Management',
      '3D Modeling',
      'Photoshop',
      'Illustrator',
      'Presentation',
    ],
  },

  // Public Administration & Government
  government: {
    label: 'Public Administration & Government',
    skills: [
      'Public Policy',
      'Policy Analysis',
      'Political Analysis',
      'Law',
      'Public Administration',
      'Government Affairs',
      'Legislative Process',
      'Community Development',
      'Social Services',
      'Public Health',
      'Budgeting',
      'Financial Management',
      'Grant Management',
      'Compliance',
      'Regulatory Affairs',
      'Lobbying',
      'Advocacy',
      'Community Engagement',
      'Public Relations',
      'Communications',
    ],
  },

  // Other Skills
  soft: {
    label: 'Soft & General Skills',
    skills: [
      'Communication',
      'Teamwork',
      'Leadership',
      'Problem Solving',
      'Critical Thinking',
      'Creativity',
      'Time Management',
      'Organization',
      'Adaptability',
      'Flexibility',
      'Learning Ability',
      'Attention to Detail',
      'Accountability',
      'Initiative',
      'Collaboration',
      'Negotiation',
      'Persuasion',
      'Conflict Resolution',
      'Empathy',
      'Active Listening',
      'Emotional Intelligence',
      'Patience',
      'Resilience',
      'Decision Making',
      'Analytical Thinking',
      'Strategic Thinking',
      'Business Acumen',
      'Customer Focus',
      'Quality Mindset',
    ],
  },
};

// Flatten all skills for easy searching
export const allSkills = Object.values(skillsDatabase)
  .reduce((acc, category) => {
    return [...acc, ...category.skills];
  }, [])
  .sort();

// Get skills by category
export const getSkillsByCategory = category => {
  return skillsDatabase[category]?.skills || [];
};

// Get category label
export const getCategoryLabel = category => {
  return skillsDatabase[category]?.label || category;
};

// Get all categories
export const getAllCategories = () => {
  return Object.keys(skillsDatabase);
};

// Search skills
export const searchSkills = query => {
  const lowerQuery = query.toLowerCase();
  return allSkills.filter(skill => skill.toLowerCase().includes(lowerQuery));
};

// Get category for a skill
export const getCategoryForSkill = skill => {
  for (const [category, data] of Object.entries(skillsDatabase)) {
    if (data.skills.includes(skill)) {
      return category;
    }
  }
  return null;
};
