const mongoose = require('mongoose');
const dotenv = require('dotenv');
const Internship = require('./models/Internship');
const User = require('./models/User');

dotenv.config();

const seedInternships = async () => {
  try {
    // Connect to MongoDB
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('Connected to MongoDB');

    // Find or create a company user for posting internships
    let companyUser = await User.findOne({ email: 'demo-company@evleene.com' });

    if (!companyUser) {
      companyUser = await User.create({
        name: 'EVLEENE Demo Company',
        email: 'demo-company@evleene.com',
        password: 'Demo@123',
        role: 'company',
      });
      console.log('Created demo company user');
    }

    // Clear existing internships
    await Internship.deleteMany({});
    console.log('Cleared existing internships');

    // Sample internships data
    const internships = [
      {
        title: 'Software Development Intern',
        company: 'Google Germany',
        logo: 'G',
        logoColor: 'bg-blue-500',
        description:
          'Join our innovative team to work on cutting-edge web technologies. You will collaborate with experienced developers on real-world projects using React, Node.js, and TypeScript.',
        location: 'Berlin',
        duration: '6 months',
        stipend: 1200,
        type: 'On-site',
        category: 'Technology',
        tags: ['React', 'Node.js', 'TypeScript', 'JavaScript', 'Git'],
        requirements: [
          'Currently enrolled in Computer Science or related field',
          'Strong knowledge of JavaScript and React',
          'Familiarity with Node.js and TypeScript',
          'Good communication skills in English',
          'Problem-solving mindset',
        ],
        responsibilities: [
          'Develop and maintain web applications',
          'Collaborate with cross-functional teams',
          'Write clean, maintainable code',
          'Participate in code reviews',
          'Learn from senior developers',
        ],
        postedBy: companyUser._id,
        companyEmail: companyUser.email,
        isHot: true,
        isNew: true,
        applicants: 45,
        startDate: new Date('2026-03-01'),
        deadline: new Date('2026-02-20'),
      },
      {
        title: 'UX/UI Design Intern',
        company: 'SAP',
        logo: 'S',
        logoColor: 'bg-blue-600',
        description:
          'Create beautiful and intuitive user interfaces for enterprise software. Work with our design team to research user needs and design solutions.',
        location: 'Berlin',
        duration: '4 months',
        stipend: 1000,
        type: 'Hybrid',
        category: 'Design',
        tags: ['Figma', 'UI/UX', 'Prototyping', 'User Research', 'Adobe XD'],
        requirements: [
          'Currently enrolled in Design or related field',
          'Portfolio demonstrating UI/UX projects',
          'Proficiency in Figma or similar tools',
          'Understanding of design principles',
          'Attention to detail',
        ],
        responsibilities: [
          'Design user interfaces for web applications',
          'Conduct user research and usability testing',
          'Create wireframes and prototypes',
          'Collaborate with developers',
          'Maintain design system',
        ],
        postedBy: companyUser._id,
        companyEmail: companyUser.email,
        isHot: false,
        isNew: true,
        applicants: 32,
        startDate: new Date('2026-03-15'),
        deadline: new Date('2026-02-25'),
      },
      {
        title: 'Data Science Intern',
        company: 'Zalando',
        logo: 'Z',
        logoColor: 'bg-orange-500',
        description:
          'Work on machine learning projects analyzing customer behavior and optimizing recommendation systems using Python and modern ML frameworks.',
        location: 'Berlin',
        duration: '6 months',
        stipend: 1300,
        type: 'Hybrid',
        category: 'Technology',
        tags: ['Python', 'Machine Learning', 'SQL', 'TensorFlow', 'Data Analysis'],
        requirements: [
          'Enrolled in Data Science, Statistics, or related field',
          'Strong Python programming skills',
          'Knowledge of ML algorithms and statistics',
          'Experience with SQL and data analysis',
          'Analytical thinking',
        ],
        responsibilities: [
          'Analyze large datasets to extract insights',
          'Build and train machine learning models',
          'Optimize recommendation algorithms',
          'Collaborate with product teams',
          'Present findings to stakeholders',
        ],
        postedBy: companyUser._id,
        companyEmail: companyUser.email,
        isHot: true,
        isNew: true,
        applicants: 67,
        startDate: new Date('2026-03-01'),
        deadline: new Date('2026-02-18'),
      },
      {
        title: 'Marketing & Social Media Intern',
        company: 'Adidas',
        logo: 'A',
        logoColor: 'bg-gray-800',
        description:
          'Join our marketing team to create engaging content and manage social media campaigns for our sports brand.',
        location: 'Munich',
        duration: '3 months',
        stipend: 900,
        type: 'On-site',
        category: 'Marketing',
        tags: ['Digital Marketing', 'Social Media', 'Content Creation', 'SEO', 'Analytics'],
        requirements: [
          'Enrolled in Marketing, Communications, or related field',
          'Strong writing and communication skills',
          'Familiarity with social media platforms',
          'Creative mindset',
          'Basic knowledge of marketing analytics',
        ],
        responsibilities: [
          'Create content for social media channels',
          'Monitor and respond to social media engagement',
          'Assist in campaign planning and execution',
          'Analyze campaign performance metrics',
          'Research market trends',
        ],
        postedBy: companyUser._id,
        companyEmail: companyUser.email,
        isHot: false,
        isNew: false,
        applicants: 28,
        startDate: new Date('2026-03-10'),
        deadline: new Date('2026-02-22'),
      },
      {
        title: 'Mobile App Developer Intern',
        company: 'Deutsche Bank',
        logo: 'DB',
        logoColor: 'bg-indigo-600',
        description:
          'Develop mobile banking applications using React Native. Work on features that millions of users interact with daily.',
        location: 'Frankfurt',
        duration: '5 months',
        stipend: 1400,
        type: 'Hybrid',
        category: 'Technology',
        tags: ['React Native', 'iOS', 'Android', 'Mobile Development', 'JavaScript'],
        requirements: [
          'Enrolled in Computer Science or related field',
          'Experience with React Native or native mobile development',
          'Understanding of mobile app architecture',
          'Knowledge of RESTful APIs',
          'Strong problem-solving skills',
        ],
        responsibilities: [
          'Develop features for mobile banking app',
          'Write unit and integration tests',
          'Optimize app performance',
          'Fix bugs and improve user experience',
          'Collaborate with backend team',
        ],
        postedBy: companyUser._id,
        companyEmail: companyUser.email,
        isHot: true,
        isNew: false,
        applicants: 54,
        startDate: new Date('2026-04-01'),
        deadline: new Date('2026-03-01'),
      },
      {
        title: 'Content Marketing Intern',
        company: 'Booking.com',
        logo: 'BC',
        logoColor: 'bg-blue-700',
        description:
          'Create compelling content for our travel platform. Write blog posts, manage email campaigns, and optimize content for SEO.',
        location: 'Hamburg',
        duration: '4 months',
        stipend: 850,
        type: 'Remote',
        category: 'Marketing',
        tags: ['Content Writing', 'SEO', 'Copywriting', 'Email Marketing', 'Blog'],
        requirements: [
          'Excellent writing skills in English',
          'Passion for travel and storytelling',
          'Basic SEO knowledge',
          'Creativity and attention to detail',
          'Self-motivated for remote work',
        ],
        responsibilities: [
          'Write engaging blog posts about travel',
          'Create email marketing campaigns',
          'Optimize content for search engines',
          'Research travel trends and destinations',
          'Collaborate with design team on visuals',
        ],
        postedBy: companyUser._id,
        companyEmail: companyUser.email,
        isHot: false,
        isNew: true,
        applicants: 19,
        startDate: new Date('2026-03-20'),
        deadline: new Date('2026-02-28'),
      },
      {
        title: 'Backend Developer Intern',
        company: 'Siemens',
        logo: 'S',
        logoColor: 'bg-teal-600',
        description:
          'Build scalable backend services for IoT applications. Work with Java, Spring Boot, and cloud technologies.',
        location: 'Munich',
        duration: '6 months',
        stipend: 1250,
        type: 'On-site',
        category: 'Technology',
        tags: ['Java', 'Spring Boot', 'REST API', 'SQL', 'AWS'],
        requirements: [
          'Enrolled in Computer Science or related field',
          'Strong Java programming skills',
          'Understanding of RESTful API design',
          'Knowledge of databases and SQL',
          'Interest in IoT and industrial technology',
        ],
        responsibilities: [
          'Develop and maintain backend services',
          'Design and implement REST APIs',
          'Optimize database queries',
          'Write comprehensive tests',
          'Document technical specifications',
        ],
        postedBy: companyUser._id,
        companyEmail: companyUser.email,
        isHot: false,
        isNew: false,
        applicants: 38,
        startDate: new Date('2026-03-15'),
        deadline: new Date('2026-02-20'),
      },
      {
        title: 'Product Management Intern',
        company: 'BMW',
        logo: 'B',
        logoColor: 'bg-blue-900',
        description:
          'Join our product team working on digital automotive solutions. Learn product strategy, roadmap planning, and agile methodologies.',
        location: 'Munich',
        duration: '5 months',
        stipend: 1100,
        type: 'Hybrid',
        category: 'Business',
        tags: ['Product Management', 'Agile', 'Strategy', 'Analytics', 'Automotive'],
        requirements: [
          'Enrolled in Business, Engineering, or related field',
          'Interest in automotive and technology',
          'Analytical and strategic thinking',
          'Good communication skills',
          'Familiarity with agile methodologies',
        ],
        responsibilities: [
          'Support product roadmap planning',
          'Conduct market and competitor research',
          'Gather and analyze user feedback',
          'Coordinate with engineering teams',
          'Participate in sprint planning meetings',
        ],
        postedBy: companyUser._id,
        companyEmail: companyUser.email,
        isHot: false,
        isNew: true,
        applicants: 41,
        startDate: new Date('2026-04-01'),
        deadline: new Date('2026-03-05'),
      },
      {
        title: 'DevOps Engineer Intern',
        company: 'Volkswagen',
        logo: 'V',
        logoColor: 'bg-blue-700',
        description:
          'Learn cloud infrastructure and CI/CD pipelines. Work with Docker, Kubernetes, and modern DevOps tools.',
        location: 'Stuttgart',
        duration: '6 months',
        stipend: 1150,
        type: 'On-site',
        category: 'Technology',
        tags: ['Docker', 'Kubernetes', 'CI/CD', 'AWS', 'Linux'],
        requirements: [
          'Enrolled in Computer Science or related field',
          'Basic understanding of Linux and networking',
          'Interest in cloud technologies',
          'Scripting knowledge (Python, Bash)',
          'Problem-solving mindset',
        ],
        responsibilities: [
          'Maintain CI/CD pipelines',
          'Deploy applications to cloud infrastructure',
          'Monitor system performance and logs',
          'Automate deployment processes',
          'Support development teams',
        ],
        postedBy: companyUser._id,
        companyEmail: companyUser.email,
        isHot: false,
        isNew: true,
        applicants: 35,
        startDate: new Date('2026-03-15'),
        deadline: new Date('2026-02-25'),
      },
      {
        title: 'Data Engineer Intern',
        company: 'Lufthansa',
        logo: 'L',
        logoColor: 'bg-yellow-500',
        description:
          'Build data pipelines and ETL processes for our airline operations. Work with big data technologies and cloud platforms.',
        location: 'Hamburg',
        duration: '5 months',
        stipend: 1200,
        type: 'Hybrid',
        category: 'Technology',
        tags: ['Python', 'SQL', 'ETL', 'Big Data', 'Cloud'],
        requirements: [
          'Enrolled in Computer Science, Data Science, or related field',
          'Strong Python and SQL skills',
          'Understanding of data modeling',
          'Interest in aviation industry',
          'Attention to detail',
        ],
        responsibilities: [
          'Build and maintain data pipelines',
          'Develop ETL processes',
          'Optimize database performance',
          'Ensure data quality and integrity',
          'Create data documentation',
        ],
        postedBy: companyUser._id,
        companyEmail: companyUser.email,
        isHot: true,
        isNew: false,
        applicants: 29,
        startDate: new Date('2026-04-01'),
        deadline: new Date('2026-03-01'),
      },
      {
        title: 'Graphic Design Intern',
        company: 'Bayer',
        logo: 'B',
        logoColor: 'bg-green-600',
        description:
          'Create visual designs for pharmaceutical marketing campaigns. Work on branding, packaging, and digital assets.',
        location: 'Cologne',
        duration: '4 months',
        stipend: 900,
        type: 'On-site',
        category: 'Design',
        tags: [
          'Adobe Creative Suite',
          'Graphic Design',
          'Branding',
          'Print Design',
          'Digital Design',
        ],
        requirements: [
          'Enrolled in Graphic Design or related field',
          'Proficiency in Adobe Creative Suite',
          'Strong portfolio demonstrating design skills',
          'Understanding of color theory and typography',
          'Creativity and attention to detail',
        ],
        responsibilities: [
          'Design marketing materials and campaigns',
          'Create digital and print assets',
          'Support branding initiatives',
          'Collaborate with marketing team',
          'Maintain brand consistency',
        ],
        postedBy: companyUser._id,
        companyEmail: companyUser.email,
        isHot: false,
        isNew: false,
        applicants: 22,
        startDate: new Date('2026-03-15'),
        deadline: new Date('2026-02-28'),
      },
      {
        title: 'Financial Analyst Intern',
        company: 'Commerzbank',
        logo: 'C',
        logoColor: 'bg-yellow-600',
        description:
          'Analyze financial data and support investment decisions. Learn financial modeling and market analysis.',
        location: 'Frankfurt',
        duration: '6 months',
        stipend: 1350,
        type: 'On-site',
        category: 'Finance',
        tags: ['Financial Analysis', 'Excel', 'Modeling', 'Investment', 'Banking'],
        requirements: [
          'Enrolled in Finance, Economics, or related field',
          'Strong Excel and analytical skills',
          'Understanding of financial markets',
          'Detail-oriented and accurate',
          'Interest in banking industry',
        ],
        responsibilities: [
          'Analyze financial statements and data',
          'Build financial models',
          'Support investment research',
          'Prepare reports for senior analysts',
          'Monitor market trends',
        ],
        postedBy: companyUser._id,
        companyEmail: companyUser.email,
        isHot: false,
        isNew: false,
        applicants: 43,
        startDate: new Date('2026-03-01'),
        deadline: new Date('2026-02-15'),
      },
      {
        title: 'Cybersecurity Intern',
        company: 'Allianz',
        logo: 'A',
        logoColor: 'bg-blue-800',
        description:
          'Learn about information security, threat detection, and security best practices in financial services.',
        location: 'Munich',
        duration: '6 months',
        stipend: 1300,
        type: 'Hybrid',
        category: 'Technology',
        tags: ['Cybersecurity', 'Network Security', 'Python', 'Penetration Testing', 'Security'],
        requirements: [
          'Enrolled in Computer Science, Cybersecurity, or related field',
          'Understanding of networking and security concepts',
          'Interest in ethical hacking and security',
          'Basic scripting knowledge',
          'Detail-oriented mindset',
        ],
        responsibilities: [
          'Monitor security systems and alerts',
          'Assist in vulnerability assessments',
          'Support incident response activities',
          'Research security threats and trends',
          'Document security procedures',
        ],
        postedBy: companyUser._id,
        companyEmail: companyUser.email,
        isHot: true,
        isNew: true,
        applicants: 31,
        startDate: new Date('2026-04-01'),
        deadline: new Date('2026-03-10'),
      },
      {
        title: 'Machine Learning Intern',
        company: 'Bosch',
        logo: 'B',
        logoColor: 'bg-red-600',
        description:
          'Work on AI and machine learning projects for automotive and IoT applications. Use TensorFlow and PyTorch.',
        location: 'Stuttgart',
        duration: '6 months',
        stipend: 1350,
        type: 'On-site',
        category: 'Technology',
        tags: ['TensorFlow', 'PyTorch', 'Machine Learning', 'AI', 'Python'],
        requirements: [
          'Enrolled in Computer Science, AI, or related field',
          'Strong Python programming skills',
          'Knowledge of ML algorithms and frameworks',
          'Understanding of mathematics and statistics',
          'Research-oriented mindset',
        ],
        responsibilities: [
          'Develop and train ML models',
          'Experiment with different algorithms',
          'Optimize model performance',
          'Document research findings',
          'Collaborate with engineering teams',
        ],
        postedBy: companyUser._id,
        companyEmail: companyUser.email,
        isHot: true,
        isNew: true,
        applicants: 58,
        startDate: new Date('2026-03-15'),
        deadline: new Date('2026-02-20'),
      },
      {
        title: 'Human Resources Intern',
        company: 'Mercedes-Benz',
        logo: 'MB',
        logoColor: 'bg-gray-700',
        description:
          'Support HR operations including recruitment, onboarding, and employee engagement initiatives.',
        location: 'Stuttgart',
        duration: '4 months',
        stipend: 950,
        type: 'On-site',
        category: 'Business',
        tags: [
          'Human Resources',
          'Recruitment',
          'Employee Relations',
          'HR Operations',
          'Communication',
        ],
        requirements: [
          'Enrolled in Human Resources, Psychology, or related field',
          'Strong interpersonal skills',
          'Organizational abilities',
          'Discretion and confidentiality',
          'Interest in automotive industry',
        ],
        responsibilities: [
          'Support recruitment processes',
          'Assist with employee onboarding',
          'Coordinate HR events and initiatives',
          'Maintain HR databases',
          'Prepare HR reports and documentation',
        ],
        postedBy: companyUser._id,
        companyEmail: companyUser.email,
        isHot: false,
        isNew: true,
        applicants: 26,
        startDate: new Date('2026-03-20'),
        deadline: new Date('2026-02-28'),
      },
    ];

    // Insert internships
    const createdInternships = await Internship.insertMany(internships);
    console.log(`✅ Successfully created ${createdInternships.length} internships`);

    // Display summary
    console.log('\n📊 Internship Summary:');
    const summary = await Internship.aggregate([
      {
        $group: {
          _id: '$location',
          count: { $sum: 1 },
          avgStipend: { $avg: '$stipend' },
        },
      },
      { $sort: { count: -1 } },
    ]);

    summary.forEach(item => {
      console.log(
        `   ${item._id}: ${item.count} internships (avg stipend: €${Math.round(item.avgStipend)})`
      );
    });

    console.log('\n✅ Database seeded successfully!');
    process.exit(0);
  } catch (error) {
    console.error('❌ Error seeding database:', error);
    process.exit(1);
  }
};

seedInternships();
